version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: dev.Dockerfile  # Specify custom Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount current directory to /app in the container
    environment:
      - FLASK_ENV=development  # Enable hot-reload for Flask
      - FLASK_DEBUG=1  # Enables debug mode
